language: node_js
node_js:
  - "6"
env:
  global:
    - STAGING_REPOSITORY=mozmar/status.ramzom.org
before_install:
  - cd ./local-dev/
install:
  - npm install
script:
  - npm test
deploy:
  - provider: script
    script: cd ${TRAVIS_BUILD_DIR} && ./bin/update-stage.sh
    skip_cleanup: true
    on:
      branch: develop-test
      repo: mozmar/status.mozmar.org
